services:
  backend:
    image: ghcr.io/kaangoker/getsubtitles-backend:latest
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/kaangoker/getsubtitles-frontend:latest
    ports:
      - "8501:8501"
    
    environment:
      - BACKEND_URL=http://backend:8000
    
    depends_on:
      - backend